twig:
    default_path: "%kernel.project_dir%/templates"
    form_themes:
        - "forms/tailwind_form_theme.html.twig"
    file_name_pattern: "*.twig"

when@test:
    twig:
        strict_variables: true
