# config/services.yaml

# 1) Le paramètre doit être au niveau racine :
parameters:
    logos_directory: "%kernel.project_dir%/public/uploads/logos"

services:
    # 2) Defaults pour tous vos services
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            # Vous pouvez binder globalement si vous avez plusieurs controllers
            $logos_directory: "%logos_directory%"

    # 3) Importez toutes vos classes src/… comme services
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
