# config/services.yaml

parameters:
    logos_directory: "%kernel.project_dir%/public/uploads/logos"
    app.docs_base_path: "%kernel.project_dir%/var/storage/docs"
    app.devis_validity_days: 30
    app.tva_default_rate: 20
    app.mail_from_address: "%env(MAILER_FROM_ADDRESS)%"
    app.mail_from_name: "%env(MAILER_FROM_NAME)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $logos_directory: "%logos_directory%"

    App\:
        resource: "../src/*"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    App\EventSubscriber\ActivitySubscriber:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: postFlush }

    App\Service\DocumentNumberGenerator: ~

    App\Service\DevisSnapshotBuilder:
        arguments:
            $defaultValidityDays: "%app.devis_validity_days%"
            $defaultTvaRate: "%app.tva_default_rate%"

    App\Service\DocumentPdfGenerator:
        arguments:
            $basePath: "%app.docs_base_path%"
    App\Repository\:
        resource: "../src/Repository"
        autowire: true
        autoconfigure: true
    App\Repository\DocumentRepository:
        arguments:
            - "@doctrine" # ManagerRegistry
        tags: ["doctrine.repository_service"]
    App\MessageHandler\SendDocumentEmailHandler:
        arguments:
            $defaultFrom: "%app.mail_from_address%"
            $defaultFromName: "%app.mail_from_name%"
